head(iris)
clusters<- hclust (dist(iris[,3:4]))
plot(clusters)
clustercut <-cutree(cluster,3)
table (clustercut,iris$Species)
cluster<-hclust(dist(iris[,3:4]),method='complete')
plot(clusters)
clustercut<-cutree(clusters,3)
table(clustercut,iris$Species)
ggplot(iris,aes(Petal.Length,Petal.Width, color=Species))+geom_point(alpha=0.4,size=3.5)+geom_point(col=clustercut)+scale_color_manual(values = c('black','red','green'))

